# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gobgp.proto for package 'gobgpapi'
# Original file comments:
# Copyright (C) 2015-2017 Nippon Telegraph and Telephone Corporation.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

require 'grpc'
require_relative 'gobgp_pb'

module Gobgpapi
  module GobgpApi
    # Interface exported by the server.
    #
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gobgpapi.GobgpApi'

      rpc :StartServer, StartServerRequest, StartServerResponse
      rpc :StopServer, StopServerRequest, StopServerResponse
      rpc :GetServer, GetServerRequest, GetServerResponse
      rpc :AddNeighbor, AddNeighborRequest, AddNeighborResponse
      rpc :DeleteNeighbor, DeleteNeighborRequest, DeleteNeighborResponse
      rpc :UpdateNeighbor, UpdateNeighborRequest, UpdateNeighborResponse
      rpc :GetNeighbor, GetNeighborRequest, GetNeighborResponse
      rpc :ResetNeighbor, ResetNeighborRequest, ResetNeighborResponse
      rpc :SoftResetNeighbor, SoftResetNeighborRequest, SoftResetNeighborResponse
      rpc :ShutdownNeighbor, ShutdownNeighborRequest, ShutdownNeighborResponse
      rpc :EnableNeighbor, EnableNeighborRequest, EnableNeighborResponse
      rpc :DisableNeighbor, DisableNeighborRequest, DisableNeighborResponse
      rpc :GetRib, GetRibRequest, GetRibResponse
      rpc :GetPath, GetPathRequest, stream(Path)
      rpc :ValidateRib, ValidateRibRequest, ValidateRibResponse
      rpc :AddPath, AddPathRequest, AddPathResponse
      rpc :DeletePath, DeletePathRequest, DeletePathResponse
      rpc :MonitorRib, MonitorRibRequest, stream(Destination)
      rpc :MonitorPeerState, Arguments, stream(Peer)
      rpc :EnableMrt, EnableMrtRequest, EnableMrtResponse
      rpc :DisableMrt, DisableMrtRequest, DisableMrtResponse
      rpc :InjectMrt, stream(InjectMrtRequest), InjectMrtResponse
      rpc :AddBmp, AddBmpRequest, AddBmpResponse
      rpc :DeleteBmp, DeleteBmpRequest, DeleteBmpResponse
      rpc :GetRpki, GetRpkiRequest, GetRpkiResponse
      rpc :AddRpki, AddRpkiRequest, AddRpkiResponse
      rpc :DeleteRpki, DeleteRpkiRequest, DeleteRpkiResponse
      rpc :EnableRpki, EnableRpkiRequest, EnableRpkiResponse
      rpc :DisableRpki, DisableRpkiRequest, DisableRpkiResponse
      rpc :ResetRpki, ResetRpkiRequest, ResetRpkiResponse
      rpc :SoftResetRpki, SoftResetRpkiRequest, SoftResetRpkiResponse
      rpc :GetRoa, GetRoaRequest, GetRoaResponse
      rpc :EnableZebra, EnableZebraRequest, EnableZebraResponse
      rpc :AddVrf, AddVrfRequest, AddVrfResponse
      rpc :DeleteVrf, DeleteVrfRequest, DeleteVrfResponse
      rpc :GetVrf, GetVrfRequest, GetVrfResponse
      rpc :GetDefinedSet, GetDefinedSetRequest, GetDefinedSetResponse
      rpc :AddDefinedSet, AddDefinedSetRequest, AddDefinedSetResponse
      rpc :DeleteDefinedSet, DeleteDefinedSetRequest, DeleteDefinedSetResponse
      rpc :ReplaceDefinedSet, ReplaceDefinedSetRequest, ReplaceDefinedSetResponse
      rpc :GetStatement, GetStatementRequest, GetStatementResponse
      rpc :AddStatement, AddStatementRequest, AddStatementResponse
      rpc :DeleteStatement, DeleteStatementRequest, DeleteStatementResponse
      rpc :ReplaceStatement, ReplaceStatementRequest, ReplaceStatementResponse
      rpc :GetPolicy, GetPolicyRequest, GetPolicyResponse
      rpc :AddPolicy, AddPolicyRequest, AddPolicyResponse
      rpc :DeletePolicy, DeletePolicyRequest, DeletePolicyResponse
      rpc :ReplacePolicy, ReplacePolicyRequest, ReplacePolicyResponse
      rpc :GetPolicyAssignment, GetPolicyAssignmentRequest, GetPolicyAssignmentResponse
      rpc :AddPolicyAssignment, AddPolicyAssignmentRequest, AddPolicyAssignmentResponse
      rpc :DeletePolicyAssignment, DeletePolicyAssignmentRequest, DeletePolicyAssignmentResponse
      rpc :ReplacePolicyAssignment, ReplacePolicyAssignmentRequest, ReplacePolicyAssignmentResponse
      rpc :GetRibInfo, GetRibInfoRequest, GetRibInfoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
