# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gobgp.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gobgpapi.GetNeighborRequest" do
    optional :enableAdvertised, :bool, 1
    optional :address, :string, 2
  end
  add_message "gobgpapi.GetNeighborResponse" do
    repeated :peers, :message, 1, "gobgpapi.Peer"
  end
  add_message "gobgpapi.Arguments" do
    optional :resource, :enum, 1, "gobgpapi.Resource"
    optional :family, :uint32, 2
    optional :name, :string, 3
    optional :current, :bool, 4
  end
  add_message "gobgpapi.AddPathRequest" do
    optional :resource, :enum, 1, "gobgpapi.Resource"
    optional :vrf_id, :string, 2
    optional :path, :message, 3, "gobgpapi.Path"
  end
  add_message "gobgpapi.AddPathResponse" do
    optional :uuid, :bytes, 1
  end
  add_message "gobgpapi.DeletePathRequest" do
    optional :resource, :enum, 1, "gobgpapi.Resource"
    optional :vrf_id, :string, 2
    optional :family, :uint32, 3
    optional :path, :message, 4, "gobgpapi.Path"
    optional :uuid, :bytes, 5
  end
  add_message "gobgpapi.DeletePathResponse" do
  end
  add_message "gobgpapi.AddNeighborRequest" do
    optional :peer, :message, 1, "gobgpapi.Peer"
  end
  add_message "gobgpapi.AddNeighborResponse" do
  end
  add_message "gobgpapi.DeleteNeighborRequest" do
    optional :peer, :message, 1, "gobgpapi.Peer"
  end
  add_message "gobgpapi.DeleteNeighborResponse" do
  end
  add_message "gobgpapi.UpdateNeighborRequest" do
    optional :peer, :message, 1, "gobgpapi.Peer"
    optional :do_soft_reset_in, :bool, 2
  end
  add_message "gobgpapi.UpdateNeighborResponse" do
    optional :needs_soft_reset_in, :bool, 1
  end
  add_message "gobgpapi.ResetNeighborRequest" do
    optional :address, :string, 1
    optional :communication, :string, 2
  end
  add_message "gobgpapi.ResetNeighborResponse" do
  end
  add_message "gobgpapi.SoftResetNeighborRequest" do
    optional :address, :string, 1
    optional :direction, :enum, 2, "gobgpapi.SoftResetNeighborRequest.SoftResetDirection"
  end
  add_enum "gobgpapi.SoftResetNeighborRequest.SoftResetDirection" do
    value :IN, 0
    value :OUT, 1
    value :BOTH, 2
  end
  add_message "gobgpapi.SoftResetNeighborResponse" do
  end
  add_message "gobgpapi.ShutdownNeighborRequest" do
    optional :address, :string, 1
    optional :communication, :string, 2
  end
  add_message "gobgpapi.ShutdownNeighborResponse" do
  end
  add_message "gobgpapi.EnableNeighborRequest" do
    optional :address, :string, 1
  end
  add_message "gobgpapi.EnableNeighborResponse" do
  end
  add_message "gobgpapi.DisableNeighborRequest" do
    optional :address, :string, 1
    optional :communication, :string, 2
  end
  add_message "gobgpapi.DisableNeighborResponse" do
  end
  add_message "gobgpapi.EnableMrtRequest" do
    optional :dump_type, :int32, 1
    optional :filename, :string, 2
    optional :interval, :uint64, 3
  end
  add_message "gobgpapi.EnableMrtResponse" do
  end
  add_message "gobgpapi.DisableMrtRequest" do
  end
  add_message "gobgpapi.DisableMrtResponse" do
  end
  add_message "gobgpapi.InjectMrtRequest" do
    optional :resource, :enum, 1, "gobgpapi.Resource"
    optional :vrf_id, :string, 2
    repeated :paths, :message, 3, "gobgpapi.Path"
  end
  add_message "gobgpapi.InjectMrtResponse" do
  end
  add_message "gobgpapi.AddBmpRequest" do
    optional :address, :string, 1
    optional :port, :uint32, 2
    optional :type, :enum, 3, "gobgpapi.AddBmpRequest.MonitoringPolicy"
  end
  add_enum "gobgpapi.AddBmpRequest.MonitoringPolicy" do
    value :PRE, 0
    value :POST, 1
    value :BOTH, 2
    value :LOCAL, 3
    value :ALL, 4
  end
  add_message "gobgpapi.AddBmpResponse" do
  end
  add_message "gobgpapi.DeleteBmpRequest" do
    optional :address, :string, 1
    optional :port, :uint32, 2
  end
  add_message "gobgpapi.DeleteBmpResponse" do
  end
  add_message "gobgpapi.MonitorRibRequest" do
    optional :table, :message, 1, "gobgpapi.Table"
    optional :current, :bool, 2
  end
  add_message "gobgpapi.RPKIConf" do
    optional :address, :string, 1
    optional :remote_port, :string, 2
  end
  add_message "gobgpapi.RPKIState" do
    optional :uptime, :int64, 1
    optional :downtime, :int64, 2
    optional :up, :bool, 3
    optional :record_ipv4, :uint32, 4
    optional :record_ipv6, :uint32, 5
    optional :prefix_ipv4, :uint32, 6
    optional :prefix_ipv6, :uint32, 7
    optional :serial, :uint32, 8
    optional :received_ipv4, :int64, 9
    optional :received_ipv6, :int64, 10
    optional :serial_notify, :int64, 11
    optional :cache_reset, :int64, 12
    optional :cache_response, :int64, 13
    optional :end_of_data, :int64, 14
    optional :error, :int64, 15
    optional :serial_query, :int64, 16
    optional :reset_query, :int64, 17
  end
  add_message "gobgpapi.Rpki" do
    optional :conf, :message, 1, "gobgpapi.RPKIConf"
    optional :state, :message, 2, "gobgpapi.RPKIState"
  end
  add_message "gobgpapi.GetRpkiRequest" do
    optional :family, :uint32, 1
  end
  add_message "gobgpapi.GetRpkiResponse" do
    repeated :servers, :message, 1, "gobgpapi.Rpki"
  end
  add_message "gobgpapi.AddRpkiRequest" do
    optional :address, :string, 1
    optional :port, :uint32, 2
    optional :lifetime, :int64, 3
  end
  add_message "gobgpapi.AddRpkiResponse" do
  end
  add_message "gobgpapi.DeleteRpkiRequest" do
    optional :address, :string, 1
    optional :port, :uint32, 2
  end
  add_message "gobgpapi.DeleteRpkiResponse" do
  end
  add_message "gobgpapi.EnableRpkiRequest" do
    optional :address, :string, 1
  end
  add_message "gobgpapi.EnableRpkiResponse" do
  end
  add_message "gobgpapi.DisableRpkiRequest" do
    optional :address, :string, 1
  end
  add_message "gobgpapi.DisableRpkiResponse" do
  end
  add_message "gobgpapi.ResetRpkiRequest" do
    optional :address, :string, 1
  end
  add_message "gobgpapi.ResetRpkiResponse" do
  end
  add_message "gobgpapi.SoftResetRpkiRequest" do
    optional :address, :string, 1
  end
  add_message "gobgpapi.SoftResetRpkiResponse" do
  end
  add_message "gobgpapi.EnableZebraRequest" do
    optional :url, :string, 1
    repeated :route_types, :string, 2
    optional :version, :uint32, 3
    optional :nexthop_trigger_enable, :bool, 4
    optional :nexthop_trigger_delay, :uint32, 5
  end
  add_message "gobgpapi.EnableZebraResponse" do
  end
  add_message "gobgpapi.GetVrfRequest" do
  end
  add_message "gobgpapi.GetVrfResponse" do
    repeated :vrfs, :message, 1, "gobgpapi.Vrf"
  end
  add_message "gobgpapi.AddVrfRequest" do
    optional :vrf, :message, 1, "gobgpapi.Vrf"
  end
  add_message "gobgpapi.AddVrfResponse" do
  end
  add_message "gobgpapi.DeleteVrfRequest" do
    optional :vrf, :message, 1, "gobgpapi.Vrf"
  end
  add_message "gobgpapi.DeleteVrfResponse" do
  end
  add_message "gobgpapi.GetDefinedSetRequest" do
    optional :type, :enum, 1, "gobgpapi.DefinedType"
    optional :name, :string, 2
  end
  add_message "gobgpapi.GetDefinedSetResponse" do
    repeated :sets, :message, 1, "gobgpapi.DefinedSet"
  end
  add_message "gobgpapi.AddDefinedSetRequest" do
    optional :set, :message, 1, "gobgpapi.DefinedSet"
  end
  add_message "gobgpapi.AddDefinedSetResponse" do
  end
  add_message "gobgpapi.DeleteDefinedSetRequest" do
    optional :set, :message, 1, "gobgpapi.DefinedSet"
    optional :all, :bool, 2
  end
  add_message "gobgpapi.DeleteDefinedSetResponse" do
  end
  add_message "gobgpapi.ReplaceDefinedSetRequest" do
    optional :set, :message, 1, "gobgpapi.DefinedSet"
  end
  add_message "gobgpapi.ReplaceDefinedSetResponse" do
  end
  add_message "gobgpapi.GetStatementRequest" do
  end
  add_message "gobgpapi.GetStatementResponse" do
    repeated :statements, :message, 1, "gobgpapi.Statement"
  end
  add_message "gobgpapi.AddStatementRequest" do
    optional :statement, :message, 1, "gobgpapi.Statement"
  end
  add_message "gobgpapi.AddStatementResponse" do
  end
  add_message "gobgpapi.DeleteStatementRequest" do
    optional :statement, :message, 1, "gobgpapi.Statement"
    optional :all, :bool, 2
  end
  add_message "gobgpapi.DeleteStatementResponse" do
  end
  add_message "gobgpapi.ReplaceStatementRequest" do
    optional :statement, :message, 1, "gobgpapi.Statement"
  end
  add_message "gobgpapi.ReplaceStatementResponse" do
  end
  add_message "gobgpapi.GetPolicyRequest" do
  end
  add_message "gobgpapi.GetPolicyResponse" do
    repeated :policies, :message, 1, "gobgpapi.Policy"
  end
  add_message "gobgpapi.AddPolicyRequest" do
    optional :policy, :message, 1, "gobgpapi.Policy"
    optional :refer_existing_statements, :bool, 2
  end
  add_message "gobgpapi.AddPolicyResponse" do
  end
  add_message "gobgpapi.DeletePolicyRequest" do
    optional :policy, :message, 1, "gobgpapi.Policy"
    optional :preserve_statements, :bool, 2
    optional :all, :bool, 3
  end
  add_message "gobgpapi.DeletePolicyResponse" do
  end
  add_message "gobgpapi.ReplacePolicyRequest" do
    optional :policy, :message, 1, "gobgpapi.Policy"
    optional :refer_existing_statements, :bool, 2
    optional :preserve_statements, :bool, 3
  end
  add_message "gobgpapi.ReplacePolicyResponse" do
  end
  add_message "gobgpapi.GetPolicyAssignmentRequest" do
    optional :assignment, :message, 1, "gobgpapi.PolicyAssignment"
  end
  add_message "gobgpapi.GetPolicyAssignmentResponse" do
    optional :assignment, :message, 1, "gobgpapi.PolicyAssignment"
  end
  add_message "gobgpapi.AddPolicyAssignmentRequest" do
    optional :assignment, :message, 1, "gobgpapi.PolicyAssignment"
  end
  add_message "gobgpapi.AddPolicyAssignmentResponse" do
  end
  add_message "gobgpapi.DeletePolicyAssignmentRequest" do
    optional :assignment, :message, 1, "gobgpapi.PolicyAssignment"
    optional :all, :bool, 2
  end
  add_message "gobgpapi.DeletePolicyAssignmentResponse" do
  end
  add_message "gobgpapi.ReplacePolicyAssignmentRequest" do
    optional :assignment, :message, 1, "gobgpapi.PolicyAssignment"
  end
  add_message "gobgpapi.ReplacePolicyAssignmentResponse" do
  end
  add_message "gobgpapi.GetServerRequest" do
  end
  add_message "gobgpapi.GetServerResponse" do
    optional :global, :message, 1, "gobgpapi.Global"
  end
  add_message "gobgpapi.StartServerRequest" do
    optional :global, :message, 1, "gobgpapi.Global"
  end
  add_message "gobgpapi.StartServerResponse" do
  end
  add_message "gobgpapi.StopServerRequest" do
  end
  add_message "gobgpapi.StopServerResponse" do
  end
  add_message "gobgpapi.RPKIValidation" do
    optional :state, :enum, 1, "gobgpapi.RPKIValidation.State"
    optional :reason, :enum, 2, "gobgpapi.RPKIValidation.Reason"
    repeated :matched, :message, 3, "gobgpapi.Roa"
    repeated :unmatched_as, :message, 4, "gobgpapi.Roa"
    repeated :unmatched_length, :message, 5, "gobgpapi.Roa"
  end
  add_enum "gobgpapi.RPKIValidation.State" do
    value :STATE_NONE, 0
    value :STATE_NOT_FOUND, 1
    value :STATE_VALID, 2
    value :STATE_INVALID, 3
  end
  add_enum "gobgpapi.RPKIValidation.Reason" do
    value :REASOT_NONE, 0
    value :REASON_AS, 1
    value :REASON_LENGTH, 2
  end
  add_message "gobgpapi.Path" do
    optional :nlri, :bytes, 1
    repeated :pattrs, :bytes, 2
    optional :age, :int64, 3
    optional :best, :bool, 4
    optional :is_withdraw, :bool, 5
    optional :validation, :int32, 6
    optional :validation_detail, :message, 7, "gobgpapi.RPKIValidation"
    optional :no_implicit_withdraw, :bool, 8
    optional :family, :uint32, 9
    optional :source_asn, :uint32, 10
    optional :source_id, :string, 11
    optional :filtered, :bool, 12
    optional :stale, :bool, 13
    optional :is_from_external, :bool, 14
    optional :neighbor_ip, :string, 15
    optional :uuid, :bytes, 16
    optional :is_nexthop_invalid, :bool, 17
    optional :identifier, :uint32, 18
    optional :local_identifier, :uint32, 19
    optional :any_nlri, :message, 20, "google.protobuf.Any"
    repeated :any_pattrs, :message, 21, "google.protobuf.Any"
  end
  add_message "gobgpapi.Destination" do
    optional :prefix, :string, 1
    repeated :paths, :message, 2, "gobgpapi.Path"
    optional :longer_prefixes, :bool, 3
    optional :shorter_prefixes, :bool, 4
  end
  add_message "gobgpapi.Table" do
    optional :type, :enum, 1, "gobgpapi.Resource"
    optional :name, :string, 2
    optional :family, :uint32, 3
    repeated :destinations, :message, 4, "gobgpapi.Destination"
    optional :post_policy, :bool, 5
  end
  add_message "gobgpapi.GetRibRequest" do
    optional :table, :message, 1, "gobgpapi.Table"
  end
  add_message "gobgpapi.GetRibResponse" do
    optional :table, :message, 1, "gobgpapi.Table"
  end
  add_message "gobgpapi.TableLookupPrefix" do
    optional :prefix, :string, 1
    optional :lookup_option, :enum, 2, "gobgpapi.TableLookupOption"
  end
  add_message "gobgpapi.GetPathRequest" do
    optional :type, :enum, 1, "gobgpapi.Resource"
    optional :name, :string, 2
    optional :family, :uint32, 3
    repeated :prefixes, :message, 4, "gobgpapi.TableLookupPrefix"
  end
  add_message "gobgpapi.ValidateRibRequest" do
    optional :type, :enum, 1, "gobgpapi.Resource"
    optional :family, :uint32, 2
    optional :prefix, :string, 3
  end
  add_message "gobgpapi.ValidateRibResponse" do
  end
  add_message "gobgpapi.Peer" do
    repeated :families, :uint32, 1
    optional :apply_policy, :message, 2, "gobgpapi.ApplyPolicy"
    optional :conf, :message, 3, "gobgpapi.PeerConf"
    optional :ebgp_multihop, :message, 4, "gobgpapi.EbgpMultihop"
    optional :route_reflector, :message, 5, "gobgpapi.RouteReflector"
    optional :info, :message, 6, "gobgpapi.PeerState"
    optional :timers, :message, 7, "gobgpapi.Timers"
    optional :transport, :message, 8, "gobgpapi.Transport"
    optional :route_server, :message, 9, "gobgpapi.RouteServer"
    optional :graceful_restart, :message, 10, "gobgpapi.GracefulRestart"
    repeated :afi_safis, :message, 11, "gobgpapi.AfiSafi"
    optional :add_paths, :message, 12, "gobgpapi.AddPaths"
  end
  add_message "gobgpapi.ApplyPolicy" do
    optional :in_policy, :message, 1, "gobgpapi.PolicyAssignment"
    optional :export_policy, :message, 2, "gobgpapi.PolicyAssignment"
    optional :import_policy, :message, 3, "gobgpapi.PolicyAssignment"
  end
  add_message "gobgpapi.PrefixLimit" do
    optional :family, :uint32, 1
    optional :max_prefixes, :uint32, 2
    optional :shutdown_threshold_pct, :uint32, 3
  end
  add_message "gobgpapi.PeerConf" do
    optional :auth_password, :string, 1
    optional :description, :string, 2
    optional :local_as, :uint32, 3
    optional :neighbor_address, :string, 4
    optional :peer_as, :uint32, 5
    optional :peer_group, :string, 6
    optional :peer_type, :uint32, 7
    optional :remove_private_as, :enum, 8, "gobgpapi.PeerConf.RemovePrivateAs"
    optional :route_flap_damping, :bool, 9
    optional :send_community, :uint32, 10
    repeated :remote_cap, :bytes, 11
    repeated :local_cap, :bytes, 12
    optional :id, :string, 13
    repeated :prefix_limits, :message, 14, "gobgpapi.PrefixLimit"
    optional :local_address, :string, 15
    optional :neighbor_interface, :string, 16
    optional :vrf, :string, 17
    optional :allow_own_as, :uint32, 18
    optional :replace_peer_as, :bool, 19
  end
  add_enum "gobgpapi.PeerConf.RemovePrivateAs" do
    value :NONE, 0
    value :ALL, 1
    value :REPLACE, 2
  end
  add_message "gobgpapi.EbgpMultihop" do
    optional :enabled, :bool, 1
    optional :multihop_ttl, :uint32, 2
  end
  add_message "gobgpapi.RouteReflector" do
    optional :route_reflector_client, :bool, 1
    optional :route_reflector_cluster_id, :string, 2
  end
  add_message "gobgpapi.PeerState" do
    optional :auth_password, :string, 1
    optional :description, :string, 2
    optional :local_as, :uint32, 3
    optional :messages, :message, 4, "gobgpapi.Messages"
    optional :neighbor_address, :string, 5
    optional :peer_as, :uint32, 6
    optional :peer_group, :string, 7
    optional :peer_type, :uint32, 8
    optional :queues, :message, 9, "gobgpapi.Queues"
    optional :remove_private_as, :uint32, 10
    optional :route_flap_damping, :bool, 11
    optional :send_community, :uint32, 12
    optional :session_state, :uint32, 13
    repeated :supported_capabilities, :string, 14
    optional :bgp_state, :string, 15
    optional :admin_state, :enum, 16, "gobgpapi.PeerState.AdminState"
    optional :received, :uint32, 17
    optional :accepted, :uint32, 18
    optional :advertised, :uint32, 19
    optional :out_q, :uint32, 20
    optional :flops, :uint32, 21
  end
  add_enum "gobgpapi.PeerState.AdminState" do
    value :UP, 0
    value :DOWN, 1
    value :PFX_CT, 2
  end
  add_message "gobgpapi.Messages" do
    optional :received, :message, 1, "gobgpapi.Message"
    optional :sent, :message, 2, "gobgpapi.Message"
  end
  add_message "gobgpapi.Message" do
    optional :NOTIFICATION, :uint64, 1
    optional :UPDATE, :uint64, 2
    optional :OPEN, :uint64, 3
    optional :KEEPALIVE, :uint64, 4
    optional :REFRESH, :uint64, 5
    optional :DISCARDED, :uint64, 6
    optional :TOTAL, :uint64, 7
  end
  add_message "gobgpapi.Queues" do
    optional :input, :uint32, 1
    optional :output, :uint32, 2
  end
  add_message "gobgpapi.Timers" do
    optional :config, :message, 1, "gobgpapi.TimersConfig"
    optional :state, :message, 2, "gobgpapi.TimersState"
  end
  add_message "gobgpapi.TimersConfig" do
    optional :connect_retry, :uint64, 1
    optional :hold_time, :uint64, 2
    optional :keepalive_interval, :uint64, 3
    optional :minimum_advertisement_interval, :uint64, 4
  end
  add_message "gobgpapi.TimersState" do
    optional :connect_retry, :uint64, 1
    optional :hold_time, :uint64, 2
    optional :keepalive_interval, :uint64, 3
    optional :minimum_advertisement_interval, :uint64, 4
    optional :negotiated_hold_time, :uint64, 5
    optional :uptime, :uint64, 6
    optional :downtime, :uint64, 7
  end
  add_message "gobgpapi.Transport" do
    optional :local_address, :string, 1
    optional :local_port, :uint32, 2
    optional :mtu_discovery, :bool, 3
    optional :passive_mode, :bool, 4
    optional :remote_address, :string, 5
    optional :remote_port, :uint32, 6
    optional :tcp_mss, :uint32, 7
  end
  add_message "gobgpapi.RouteServer" do
    optional :route_server_client, :bool, 1
  end
  add_message "gobgpapi.GracefulRestart" do
    optional :enabled, :bool, 1
    optional :restart_time, :uint32, 2
    optional :helper_only, :bool, 3
    optional :deferral_time, :uint32, 4
    optional :notification_enabled, :bool, 5
    optional :longlived_enabled, :bool, 6
  end
  add_message "gobgpapi.MpGracefulRestartConfig" do
    optional :enabled, :bool, 1
  end
  add_message "gobgpapi.MpGracefulRestartState" do
    optional :enabled, :bool, 1
    optional :received, :bool, 2
    optional :advertised, :bool, 3
    optional :end_of_rib_received, :bool, 4
    optional :end_of_rib_sent, :bool, 5
  end
  add_message "gobgpapi.MpGracefulRestart" do
    optional :config, :message, 1, "gobgpapi.MpGracefulRestartConfig"
    optional :state, :message, 2, "gobgpapi.MpGracefulRestartState"
  end
  add_message "gobgpapi.AfiSafiConfig" do
    optional :family, :uint32, 1
    optional :enabled, :bool, 2
  end
  add_message "gobgpapi.AfiSafiState" do
    optional :family, :uint32, 1
    optional :enabled, :bool, 2
    optional :total_paths, :uint32, 3
    optional :total_prefixes, :uint32, 4
  end
  add_message "gobgpapi.RouteSelectionOptionsConfig" do
    optional :always_compare_med, :bool, 1
    optional :ignore_as_path_length, :bool, 2
    optional :external_compare_router_id, :bool, 3
    optional :advertise_inactive_routes, :bool, 4
    optional :enable_aigp, :bool, 5
    optional :ignore_next_hop_igp_metric, :bool, 6
  end
  add_message "gobgpapi.RouteSelectionOptionsState" do
    optional :always_compare_med, :bool, 1
    optional :ignore_as_path_length, :bool, 2
    optional :external_compare_router_id, :bool, 3
    optional :advertise_inactive_routes, :bool, 4
    optional :enable_aigp, :bool, 5
    optional :ignore_next_hop_igp_metric, :bool, 6
  end
  add_message "gobgpapi.RouteSelectionOptions" do
    optional :config, :message, 1, "gobgpapi.RouteSelectionOptionsConfig"
    optional :state, :message, 2, "gobgpapi.RouteSelectionOptionsState"
  end
  add_message "gobgpapi.UseMultiplePathsConfig" do
    optional :enabled, :bool, 1
  end
  add_message "gobgpapi.UseMultiplePathsState" do
    optional :enabled, :bool, 1
  end
  add_message "gobgpapi.EbgpConfig" do
    optional :allow_multiple_as, :bool, 1
    optional :maximum_paths, :uint32, 2
  end
  add_message "gobgpapi.EbgpState" do
    optional :allow_multiple_as, :bool, 1
    optional :maximum_paths, :uint32, 2
  end
  add_message "gobgpapi.Ebgp" do
    optional :config, :message, 1, "gobgpapi.EbgpConfig"
    optional :state, :message, 2, "gobgpapi.EbgpState"
  end
  add_message "gobgpapi.IbgpConfig" do
    optional :maximum_paths, :uint32, 1
  end
  add_message "gobgpapi.IbgpState" do
    optional :maximum_paths, :uint32, 1
  end
  add_message "gobgpapi.Ibgp" do
    optional :config, :message, 1, "gobgpapi.IbgpConfig"
    optional :state, :message, 2, "gobgpapi.IbgpState"
  end
  add_message "gobgpapi.UseMultiplePaths" do
    optional :config, :message, 1, "gobgpapi.UseMultiplePathsConfig"
    optional :state, :message, 2, "gobgpapi.UseMultiplePathsState"
    optional :ebgp, :message, 3, "gobgpapi.Ebgp"
    optional :ibgp, :message, 4, "gobgpapi.Ibgp"
  end
  add_message "gobgpapi.RouteTargetMembershipConfig" do
    optional :deferral_time, :uint32, 1
  end
  add_message "gobgpapi.RouteTargetMembershipState" do
    optional :deferral_time, :uint32, 1
  end
  add_message "gobgpapi.RouteTargetMembership" do
    optional :config, :message, 1, "gobgpapi.RouteTargetMembershipConfig"
    optional :state, :message, 2, "gobgpapi.RouteTargetMembershipState"
  end
  add_message "gobgpapi.LongLivedGracefulRestartConfig" do
    optional :enabled, :bool, 1
    optional :restart_time, :uint32, 2
  end
  add_message "gobgpapi.LongLivedGracefulRestartState" do
    optional :enabled, :bool, 1
    optional :received, :bool, 2
    optional :advertised, :bool, 3
    optional :peer_restart_time, :uint32, 4
    optional :peer_restart_timer_expired, :bool, 5
  end
  add_message "gobgpapi.LongLivedGracefulRestart" do
    optional :config, :message, 1, "gobgpapi.LongLivedGracefulRestartConfig"
    optional :state, :message, 2, "gobgpapi.LongLivedGracefulRestartState"
  end
  add_message "gobgpapi.AfiSafi" do
    optional :mp_graceful_restart, :message, 1, "gobgpapi.MpGracefulRestart"
    optional :config, :message, 2, "gobgpapi.AfiSafiConfig"
    optional :apply_policy, :message, 3, "gobgpapi.ApplyPolicy"
    optional :route_selection_options, :message, 4, "gobgpapi.RouteSelectionOptions"
    optional :use_multiple_paths, :message, 5, "gobgpapi.UseMultiplePaths"
    optional :prefix_limits, :message, 6, "gobgpapi.PrefixLimit"
    optional :route_target_membership, :message, 7, "gobgpapi.RouteTargetMembership"
    optional :long_lived_graceful_restart, :message, 8, "gobgpapi.LongLivedGracefulRestart"
    optional :add_paths, :message, 9, "gobgpapi.AddPaths"
  end
  add_message "gobgpapi.AddPathsConfig" do
    optional :receive, :bool, 1
    optional :send_max, :uint32, 2
  end
  add_message "gobgpapi.AddPathsState" do
    optional :receive, :bool, 1
    optional :send_max, :uint32, 2
  end
  add_message "gobgpapi.AddPaths" do
    optional :config, :message, 1, "gobgpapi.AddPathsConfig"
    optional :state, :message, 2, "gobgpapi.AddPathsState"
  end
  add_message "gobgpapi.Prefix" do
    optional :ip_prefix, :string, 1
    optional :mask_length_min, :uint32, 2
    optional :mask_length_max, :uint32, 3
  end
  add_message "gobgpapi.DefinedSet" do
    optional :type, :enum, 1, "gobgpapi.DefinedType"
    optional :name, :string, 2
    repeated :list, :string, 3
    repeated :prefixes, :message, 4, "gobgpapi.Prefix"
  end
  add_message "gobgpapi.MatchSet" do
    optional :type, :enum, 1, "gobgpapi.MatchType"
    optional :name, :string, 2
  end
  add_message "gobgpapi.AsPathLength" do
    optional :type, :enum, 1, "gobgpapi.AsPathLengthType"
    optional :length, :uint32, 2
  end
  add_message "gobgpapi.Conditions" do
    optional :prefix_set, :message, 1, "gobgpapi.MatchSet"
    optional :neighbor_set, :message, 2, "gobgpapi.MatchSet"
    optional :as_path_length, :message, 3, "gobgpapi.AsPathLength"
    optional :as_path_set, :message, 4, "gobgpapi.MatchSet"
    optional :community_set, :message, 5, "gobgpapi.MatchSet"
    optional :ext_community_set, :message, 6, "gobgpapi.MatchSet"
    optional :rpki_result, :int32, 7
    optional :route_type, :enum, 8, "gobgpapi.Conditions.RouteType"
    optional :large_community_set, :message, 9, "gobgpapi.MatchSet"
    repeated :next_hop_in_list, :string, 10
  end
  add_enum "gobgpapi.Conditions.RouteType" do
    value :ROUTE_TYPE_NONE, 0
    value :ROUTE_TYPE_INTERNAL, 1
    value :ROUTE_TYPE_EXTERNAL, 2
    value :ROUTE_TYPE_LOCAL, 3
  end
  add_message "gobgpapi.CommunityAction" do
    optional :type, :enum, 1, "gobgpapi.CommunityActionType"
    repeated :communities, :string, 2
  end
  add_message "gobgpapi.MedAction" do
    optional :type, :enum, 1, "gobgpapi.MedActionType"
    optional :value, :int64, 2
  end
  add_message "gobgpapi.AsPrependAction" do
    optional :asn, :uint32, 1
    optional :repeat, :uint32, 2
    optional :use_left_most, :bool, 3
  end
  add_message "gobgpapi.NexthopAction" do
    optional :address, :string, 1
    optional :self, :bool, 2
  end
  add_message "gobgpapi.LocalPrefAction" do
    optional :value, :uint32, 1
  end
  add_message "gobgpapi.Actions" do
    optional :route_action, :enum, 1, "gobgpapi.RouteAction"
    optional :community, :message, 2, "gobgpapi.CommunityAction"
    optional :med, :message, 3, "gobgpapi.MedAction"
    optional :as_prepend, :message, 4, "gobgpapi.AsPrependAction"
    optional :ext_community, :message, 5, "gobgpapi.CommunityAction"
    optional :nexthop, :message, 6, "gobgpapi.NexthopAction"
    optional :local_pref, :message, 7, "gobgpapi.LocalPrefAction"
    optional :large_community, :message, 8, "gobgpapi.CommunityAction"
  end
  add_message "gobgpapi.Statement" do
    optional :name, :string, 1
    optional :conditions, :message, 2, "gobgpapi.Conditions"
    optional :actions, :message, 3, "gobgpapi.Actions"
  end
  add_message "gobgpapi.Policy" do
    optional :name, :string, 1
    repeated :statements, :message, 2, "gobgpapi.Statement"
  end
  add_message "gobgpapi.PolicyAssignment" do
    optional :type, :enum, 1, "gobgpapi.PolicyType"
    optional :resource, :enum, 2, "gobgpapi.Resource"
    optional :name, :string, 3
    repeated :policies, :message, 4, "gobgpapi.Policy"
    optional :default, :enum, 5, "gobgpapi.RouteAction"
  end
  add_message "gobgpapi.Roa" do
    optional :as, :uint32, 1
    optional :prefixlen, :uint32, 2
    optional :maxlen, :uint32, 3
    optional :prefix, :string, 4
    optional :conf, :message, 5, "gobgpapi.RPKIConf"
  end
  add_message "gobgpapi.GetRoaRequest" do
    optional :family, :uint32, 1
  end
  add_message "gobgpapi.GetRoaResponse" do
    repeated :roas, :message, 1, "gobgpapi.Roa"
  end
  add_message "gobgpapi.Vrf" do
    optional :name, :string, 1
    optional :rd, :bytes, 2
    repeated :import_rt, :bytes, 3
    repeated :export_rt, :bytes, 4
    optional :id, :uint32, 5
  end
  add_message "gobgpapi.Global" do
    optional :as, :uint32, 1
    optional :router_id, :string, 2
    optional :listen_port, :int32, 3
    repeated :listen_addresses, :string, 4
    repeated :families, :uint32, 5
    optional :use_multiple_paths, :bool, 6
  end
  add_message "gobgpapi.TableInfo" do
    optional :type, :enum, 1, "gobgpapi.Resource"
    optional :name, :string, 2
    optional :family, :uint32, 3
    optional :num_destination, :uint64, 4
    optional :num_path, :uint64, 5
    optional :num_accepted, :uint64, 6
  end
  add_message "gobgpapi.GetRibInfoRequest" do
    optional :info, :message, 1, "gobgpapi.TableInfo"
  end
  add_message "gobgpapi.GetRibInfoResponse" do
    optional :info, :message, 1, "gobgpapi.TableInfo"
  end
  add_enum "gobgpapi.Family" do
    value :RESERVED, 0
    value :IPv4, 65537
    value :IPv6, 131073
    value :IPv4_MC, 65538
    value :IPv6_MC, 131074
    value :IPv4_MPLS, 65540
    value :IPv6_MPLS, 131076
    value :IPv4_VPN, 65664
    value :IPv6_VPN, 131200
    value :IPv4_VPN_MC, 65665
    value :IPv6_VPN_MC, 131201
    value :VPLS, 1638465
    value :EVPN, 1638470
    value :RTC, 65668
    value :IPv4_ENCAP, 65543
    value :IPv6_ENCAP, 131079
    value :FLOW_SPEC_IPv4, 65669
    value :FLOW_SPEC_IPv6, 131205
    value :FLOW_SPEC_IPv4_VPN, 65670
    value :FLOW_SPEC_IPv6_VPN, 131206
    value :FLOW_SPEC_L2_VPN, 1638534
    value :OPAQUE, 1074594033
  end
  add_enum "gobgpapi.Resource" do
    value :GLOBAL, 0
    value :LOCAL, 1
    value :ADJ_IN, 2
    value :ADJ_OUT, 3
    value :VRF, 4
  end
  add_enum "gobgpapi.TableLookupOption" do
    value :LOOKUP_EXACT, 0
    value :LOOKUP_LONGER, 1
    value :LOOKUP_SHORTER, 2
  end
  add_enum "gobgpapi.DefinedType" do
    value :PREFIX, 0
    value :NEIGHBOR, 1
    value :TAG, 2
    value :AS_PATH, 3
    value :COMMUNITY, 4
    value :EXT_COMMUNITY, 5
    value :LARGE_COMMUNITY, 6
    value :NEXT_HOP, 7
  end
  add_enum "gobgpapi.MatchType" do
    value :ANY, 0
    value :ALL, 1
    value :INVERT, 2
  end
  add_enum "gobgpapi.AsPathLengthType" do
    value :EQ, 0
    value :GE, 1
    value :LE, 2
  end
  add_enum "gobgpapi.RouteAction" do
    value :NONE, 0
    value :ACCEPT, 1
    value :REJECT, 2
  end
  add_enum "gobgpapi.CommunityActionType" do
    value :COMMUNITY_ADD, 0
    value :COMMUNITY_REMOVE, 1
    value :COMMUNITY_REPLACE, 2
  end
  add_enum "gobgpapi.MedActionType" do
    value :MED_MOD, 0
    value :MED_REPLACE, 1
  end
  add_enum "gobgpapi.PolicyType" do
    value :IN, 0
    value :IMPORT, 1
    value :EXPORT, 2
  end
end

module Gobgpapi
  GetNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetNeighborRequest").msgclass
  GetNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetNeighborResponse").msgclass
  Arguments = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Arguments").msgclass
  AddPathRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPathRequest").msgclass
  AddPathResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPathResponse").msgclass
  DeletePathRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePathRequest").msgclass
  DeletePathResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePathResponse").msgclass
  AddNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddNeighborRequest").msgclass
  AddNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddNeighborResponse").msgclass
  DeleteNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteNeighborRequest").msgclass
  DeleteNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteNeighborResponse").msgclass
  UpdateNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.UpdateNeighborRequest").msgclass
  UpdateNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.UpdateNeighborResponse").msgclass
  ResetNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ResetNeighborRequest").msgclass
  ResetNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ResetNeighborResponse").msgclass
  SoftResetNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.SoftResetNeighborRequest").msgclass
  SoftResetNeighborRequest::SoftResetDirection = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.SoftResetNeighborRequest.SoftResetDirection").enummodule
  SoftResetNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.SoftResetNeighborResponse").msgclass
  ShutdownNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ShutdownNeighborRequest").msgclass
  ShutdownNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ShutdownNeighborResponse").msgclass
  EnableNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableNeighborRequest").msgclass
  EnableNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableNeighborResponse").msgclass
  DisableNeighborRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableNeighborRequest").msgclass
  DisableNeighborResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableNeighborResponse").msgclass
  EnableMrtRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableMrtRequest").msgclass
  EnableMrtResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableMrtResponse").msgclass
  DisableMrtRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableMrtRequest").msgclass
  DisableMrtResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableMrtResponse").msgclass
  InjectMrtRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.InjectMrtRequest").msgclass
  InjectMrtResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.InjectMrtResponse").msgclass
  AddBmpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddBmpRequest").msgclass
  AddBmpRequest::MonitoringPolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddBmpRequest.MonitoringPolicy").enummodule
  AddBmpResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddBmpResponse").msgclass
  DeleteBmpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteBmpRequest").msgclass
  DeleteBmpResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteBmpResponse").msgclass
  MonitorRibRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MonitorRibRequest").msgclass
  RPKIConf = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RPKIConf").msgclass
  RPKIState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RPKIState").msgclass
  Rpki = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Rpki").msgclass
  GetRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRpkiRequest").msgclass
  GetRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRpkiResponse").msgclass
  AddRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddRpkiRequest").msgclass
  AddRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddRpkiResponse").msgclass
  DeleteRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteRpkiRequest").msgclass
  DeleteRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteRpkiResponse").msgclass
  EnableRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableRpkiRequest").msgclass
  EnableRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableRpkiResponse").msgclass
  DisableRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableRpkiRequest").msgclass
  DisableRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DisableRpkiResponse").msgclass
  ResetRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ResetRpkiRequest").msgclass
  ResetRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ResetRpkiResponse").msgclass
  SoftResetRpkiRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.SoftResetRpkiRequest").msgclass
  SoftResetRpkiResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.SoftResetRpkiResponse").msgclass
  EnableZebraRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableZebraRequest").msgclass
  EnableZebraResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EnableZebraResponse").msgclass
  GetVrfRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetVrfRequest").msgclass
  GetVrfResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetVrfResponse").msgclass
  AddVrfRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddVrfRequest").msgclass
  AddVrfResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddVrfResponse").msgclass
  DeleteVrfRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteVrfRequest").msgclass
  DeleteVrfResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteVrfResponse").msgclass
  GetDefinedSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetDefinedSetRequest").msgclass
  GetDefinedSetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetDefinedSetResponse").msgclass
  AddDefinedSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddDefinedSetRequest").msgclass
  AddDefinedSetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddDefinedSetResponse").msgclass
  DeleteDefinedSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteDefinedSetRequest").msgclass
  DeleteDefinedSetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteDefinedSetResponse").msgclass
  ReplaceDefinedSetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplaceDefinedSetRequest").msgclass
  ReplaceDefinedSetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplaceDefinedSetResponse").msgclass
  GetStatementRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetStatementRequest").msgclass
  GetStatementResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetStatementResponse").msgclass
  AddStatementRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddStatementRequest").msgclass
  AddStatementResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddStatementResponse").msgclass
  DeleteStatementRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteStatementRequest").msgclass
  DeleteStatementResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeleteStatementResponse").msgclass
  ReplaceStatementRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplaceStatementRequest").msgclass
  ReplaceStatementResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplaceStatementResponse").msgclass
  GetPolicyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetPolicyRequest").msgclass
  GetPolicyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetPolicyResponse").msgclass
  AddPolicyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPolicyRequest").msgclass
  AddPolicyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPolicyResponse").msgclass
  DeletePolicyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePolicyRequest").msgclass
  DeletePolicyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePolicyResponse").msgclass
  ReplacePolicyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplacePolicyRequest").msgclass
  ReplacePolicyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplacePolicyResponse").msgclass
  GetPolicyAssignmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetPolicyAssignmentRequest").msgclass
  GetPolicyAssignmentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetPolicyAssignmentResponse").msgclass
  AddPolicyAssignmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPolicyAssignmentRequest").msgclass
  AddPolicyAssignmentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPolicyAssignmentResponse").msgclass
  DeletePolicyAssignmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePolicyAssignmentRequest").msgclass
  DeletePolicyAssignmentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DeletePolicyAssignmentResponse").msgclass
  ReplacePolicyAssignmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplacePolicyAssignmentRequest").msgclass
  ReplacePolicyAssignmentResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ReplacePolicyAssignmentResponse").msgclass
  GetServerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetServerRequest").msgclass
  GetServerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetServerResponse").msgclass
  StartServerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.StartServerRequest").msgclass
  StartServerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.StartServerResponse").msgclass
  StopServerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.StopServerRequest").msgclass
  StopServerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.StopServerResponse").msgclass
  RPKIValidation = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RPKIValidation").msgclass
  RPKIValidation::State = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RPKIValidation.State").enummodule
  RPKIValidation::Reason = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RPKIValidation.Reason").enummodule
  Path = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Path").msgclass
  Destination = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Destination").msgclass
  Table = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Table").msgclass
  GetRibRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRibRequest").msgclass
  GetRibResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRibResponse").msgclass
  TableLookupPrefix = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.TableLookupPrefix").msgclass
  GetPathRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetPathRequest").msgclass
  ValidateRibRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ValidateRibRequest").msgclass
  ValidateRibResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ValidateRibResponse").msgclass
  Peer = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Peer").msgclass
  ApplyPolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.ApplyPolicy").msgclass
  PrefixLimit = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PrefixLimit").msgclass
  PeerConf = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PeerConf").msgclass
  PeerConf::RemovePrivateAs = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PeerConf.RemovePrivateAs").enummodule
  EbgpMultihop = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EbgpMultihop").msgclass
  RouteReflector = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteReflector").msgclass
  PeerState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PeerState").msgclass
  PeerState::AdminState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PeerState.AdminState").enummodule
  Messages = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Messages").msgclass
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Message").msgclass
  Queues = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Queues").msgclass
  Timers = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Timers").msgclass
  TimersConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.TimersConfig").msgclass
  TimersState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.TimersState").msgclass
  Transport = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Transport").msgclass
  RouteServer = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteServer").msgclass
  GracefulRestart = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GracefulRestart").msgclass
  MpGracefulRestartConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MpGracefulRestartConfig").msgclass
  MpGracefulRestartState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MpGracefulRestartState").msgclass
  MpGracefulRestart = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MpGracefulRestart").msgclass
  AfiSafiConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AfiSafiConfig").msgclass
  AfiSafiState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AfiSafiState").msgclass
  RouteSelectionOptionsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteSelectionOptionsConfig").msgclass
  RouteSelectionOptionsState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteSelectionOptionsState").msgclass
  RouteSelectionOptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteSelectionOptions").msgclass
  UseMultiplePathsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.UseMultiplePathsConfig").msgclass
  UseMultiplePathsState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.UseMultiplePathsState").msgclass
  EbgpConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EbgpConfig").msgclass
  EbgpState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.EbgpState").msgclass
  Ebgp = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Ebgp").msgclass
  IbgpConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.IbgpConfig").msgclass
  IbgpState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.IbgpState").msgclass
  Ibgp = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Ibgp").msgclass
  UseMultiplePaths = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.UseMultiplePaths").msgclass
  RouteTargetMembershipConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteTargetMembershipConfig").msgclass
  RouteTargetMembershipState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteTargetMembershipState").msgclass
  RouteTargetMembership = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteTargetMembership").msgclass
  LongLivedGracefulRestartConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.LongLivedGracefulRestartConfig").msgclass
  LongLivedGracefulRestartState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.LongLivedGracefulRestartState").msgclass
  LongLivedGracefulRestart = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.LongLivedGracefulRestart").msgclass
  AfiSafi = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AfiSafi").msgclass
  AddPathsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPathsConfig").msgclass
  AddPathsState = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPathsState").msgclass
  AddPaths = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AddPaths").msgclass
  Prefix = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Prefix").msgclass
  DefinedSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DefinedSet").msgclass
  MatchSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MatchSet").msgclass
  AsPathLength = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AsPathLength").msgclass
  Conditions = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Conditions").msgclass
  Conditions::RouteType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Conditions.RouteType").enummodule
  CommunityAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.CommunityAction").msgclass
  MedAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MedAction").msgclass
  AsPrependAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AsPrependAction").msgclass
  NexthopAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.NexthopAction").msgclass
  LocalPrefAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.LocalPrefAction").msgclass
  Actions = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Actions").msgclass
  Statement = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Statement").msgclass
  Policy = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Policy").msgclass
  PolicyAssignment = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PolicyAssignment").msgclass
  Roa = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Roa").msgclass
  GetRoaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRoaRequest").msgclass
  GetRoaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRoaResponse").msgclass
  Vrf = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Vrf").msgclass
  Global = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Global").msgclass
  TableInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.TableInfo").msgclass
  GetRibInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRibInfoRequest").msgclass
  GetRibInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.GetRibInfoResponse").msgclass
  Family = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Family").enummodule
  Resource = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.Resource").enummodule
  TableLookupOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.TableLookupOption").enummodule
  DefinedType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.DefinedType").enummodule
  MatchType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MatchType").enummodule
  AsPathLengthType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.AsPathLengthType").enummodule
  RouteAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.RouteAction").enummodule
  CommunityActionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.CommunityActionType").enummodule
  MedActionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.MedActionType").enummodule
  PolicyType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gobgpapi.PolicyType").enummodule
end
